services:
  postgres:
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:latest
